name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Test Clienting to gitee.
    - run: |
        git clone git@gitee.com:ShuYuMo2003/ShuYuMo2003.git